### ISSUE TITLE
zbuffer TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by ChristianMilianti** [facebookresearch/NGDF#16]
Hi, awesome project!
I'm trying to run it on my computer, but I'm encountering the following issue when I run `bash scripts/eval/grasp_level_set/perobj.sh -p`
Do you know what the problem could be?
```
(ngdf) christian@christian-hp-zbook:~/projects/NGDF$ bash scripts/eval/grasp_level_set/perobj.sh -p
Evaluating Bottle...
Global seed set to 0
Test: 50
pybullet build time: Mar  7 2023 13:32:16
Bottle_244894af3ba967ccd957eaf7f4edb205_0.012953570261294404
optimizing 
0: tensor([0.6035], device='cuda:0', grad_fn=<MeanBackward1>)
30: tensor([0.4997], device='cuda:0', grad_fn=<MeanBackward1>)
60: tensor([0.3975], device='cuda:0', grad_fn=<MeanBackward1>)
90: tensor([0.2993], device='cuda:0', grad_fn=<MeanBackward1>)
120: tensor([0.2257], device='cuda:0', grad_fn=<MeanBackward1>)
150: tensor([0.1721], device='cuda:0', grad_fn=<MeanBackward1>)
180: tensor([0.1128], device='cuda:0', grad_fn=<MeanBackward1>)
210: tensor([0.0763], device='cuda:0', grad_fn=<MeanBackward1>)
240: tensor([0.0650], device='cuda:0', grad_fn=<MeanBackward1>)
270: tensor([0.0606], device='cuda:0', grad_fn=<MeanBackward1>)
300: tensor([0.0590], device='cuda:0', grad_fn=<MeanBackward1>)
330: tensor([0.0579], device='cuda:0', grad_fn=<MeanBackward1>)
360: tensor([0.0569], device='cuda:0', grad_fn=<MeanBackward1>)
390: tensor([0.0558], device='cuda:0', grad_fn=<MeanBackward1>)
420: tensor([0.0550], device='cuda:0', grad_fn=<MeanBackward1>)
450: tensor([0.0544], device='cuda:0', grad_fn=<MeanBackward1>)
480: tensor([0.0534], device='cuda:0', grad_fn=<MeanBackward1>)
510: tensor([0.0525], device='cuda:0', grad_fn=<MeanBackward1>)
540: tensor([0.0511], device='cuda:0', grad_fn=<MeanBackward1>)
570: tensor([0.0498], device='cuda:0', grad_fn=<MeanBackward1>)
600: tensor([0.0489], device='cuda:0', grad_fn=<MeanBackward1>)
630: tensor([0.0481], device='cuda:0', grad_fn=<MeanBackward1>)
660: tensor([0.0475], device='cuda:0', grad_fn=<MeanBackward1>)
690: tensor([0.0469], device='cuda:0', grad_fn=<MeanBackward1>)
720: tensor([0.0463], device='cuda:0', grad_fn=<MeanBackward1>)
750: tensor([0.0457], device='cuda:0', grad_fn=<MeanBackward1>)
780: tensor([0.0452], device='cuda:0', grad_fn=<MeanBackward1>)
810: tensor([0.0449], device='cuda:0', grad_fn=<MeanBackward1>)
840: tensor([0.0447], device='cuda:0', grad_fn=<MeanBackward1>)
870: tensor([0.0445], device='cuda:0', grad_fn=<MeanBackward1>)
900: tensor([0.0443], device='cuda:0', grad_fn=<MeanBackward1>)
930: tensor([0.0440], device='cuda:0', grad_fn=<MeanBackward1>)
960: tensor([0.0437], device='cuda:0', grad_fn=<MeanBackward1>)
990: tensor([0.0435], device='cuda:0', grad_fn=<MeanBackward1>)
1020: tensor([0.0432], device='cuda:0', grad_fn=<MeanBackward1>)
1050: tensor([0.0427], device='cuda:0', grad_fn=<MeanBackward1>)
1080: tensor([0.0423], device='cuda:0', grad_fn=<MeanBackward1>)
1110: tensor([0.0419], device='cuda:0', grad_fn=<MeanBackward1>)
1140: tensor([0.0408], device='cuda:0', grad_fn=<MeanBackward1>)
1170: tensor([0.0388], device='cuda:0', grad_fn=<MeanBackward1>)
1200: tensor([0.0354], device='cuda:0', grad_fn=<MeanBackward1>)
1230: tensor([0.0293], device='cuda:0', grad_fn=<MeanBackward1>)
1260: tensor([0.0192], device='cuda:0', grad_fn=<MeanBackward1>)
1290: tensor([0.0152], device='cuda:0', grad_fn=<MeanBackward1>)
1320: tensor([0.0133], device='cuda:0', grad_fn=<MeanBackward1>)
1350: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
1380: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
1410: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
1440: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
1470: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
1500: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
1530: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
1560: tensor([0.0132], device='cuda:0', grad_fn=<MeanBackward1>)
1590: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
1620: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
1650: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
1680: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
1710: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
1740: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
1770: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
1800: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
1830: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
1860: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
1890: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
1920: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
1950: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
1980: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2010: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2040: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2070: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2100: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2130: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2160: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2190: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2220: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2250: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2280: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2310: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2340: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2370: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2400: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2430: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2460: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2490: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2520: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2550: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2580: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2610: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2640: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2670: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2700: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2730: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2760: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2790: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2820: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2850: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2880: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2910: tensor([0.0130], device='cuda:0', grad_fn=<MeanBackward1>)
2940: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
2970: tensor([0.0131], device='cuda:0', grad_fn=<MeanBackward1>)
Closest distance: 0.028
process meshes for plotly
Traceback (most recent call last):
  File "ngdf/evaluate.py", line 301, in <module>
    env, mesh, mctr_obj_T, mesh_root, obj, end_T[0]
  File "/home/christian/projects/NGDF/OMG-Planner/omg_bullet/get_bullet_labels_mp.py", line 88, in run_grasp
    env.reset(init_joints=init_joints, no_table=True, objinfos=[objinfo])
  File "/home/christian/projects/NGDF/OMG-Planner/omg_bullet/envs/acronym_env.py", line 352, in reset
    return self._get_observation()
  File "/home/christian/projects/NGDF/OMG-Planner/omg_bullet/envs/acronym_env.py", line 383, in _get_observation
    depth_zo = 2.0 * zbuffer - 1.0
TypeError: can't multiply sequence by non-int of type 'float'

```
Thanks!

**Comment by ChristianMilianti** [comment]
Solved, see #14 .
