### ISSUE TITLE
Unable to locate `acronym_multobj` dataset

### ISSUE THREAD

**Issue by paucarre** [facebookresearch/NGDF#5]
In sectoin `NGDF Training`, when trying the script to run multiobject training:
```
bash scripts/train/multobj_Bottle.sh
```
I'm getting the follownig error
```
OSError: Unable to open file (unable to open file: name = '/home/ros/NGDF/scripts/train/../../data/acronym_multobj/grasp-dataset/dataset.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```
Where can the `acronym_multobj` dataset be located?.

**Comment by thomasweng15** [comment]
Hi Pau, you can find the acronym_multobj dataset here: [Google Drive link](https://drive.google.com/drive/folders/1h88_hjP5v6cGyEOpK-g2J24FMeXKn99P?usp=share_link). I previously had only shared `acronym_perobj`; my apologies for the oversight. I updated the README in [this commit](https://github.com/facebookresearch/NGDF/commit/28cad325d987caad89d7baf15b8fb51b37b9734f) to provide the new link. Sorry again for the confusion!

**Comment by paucarre** [comment]
Thansk for hat @thomasweng15 !

I decompressed the file and I got the following error:
```
OSError: Unable to open file (unable to open file: name = '/home/ros/NGDF/scripts/train/../../data/acronym_multobj/grasp-dataset/dataset.hdf5', errno = 2, error message = 'No such file or directory', fla
gs = 0, o_flags = 0)        
```

I proceeded to copy `data/acronym_multobj/shape-dataset/dataset.hdf5` to `data/acronym_multobj/grasp-dataset/` but now I get the following error:
```
An error occurred during Hydra's exception formatting:
AssertionError()
Traceback (most recent call last):
  File "/home/ros/miniconda3/envs/ngdf/lib/python3.7/site-packages/hydra/_internal/utils.py", line 254, in run_and_report
    assert mdl is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ngdf/train.py", line 100, in <module>
    main()
  File "/home/ros/miniconda3/envs/ngdf/lib/python3.7/site-packages/hydra/main.py", line 95, in decorated_main
    config_name=config_name,
  File "/home/ros/miniconda3/envs/ngdf/lib/python3.7/site-packages/hydra/_internal/utils.py", line 396, in _run_hydra
    overrides=overrides,
  File "/home/ros/miniconda3/envs/ngdf/lib/python3.7/site-packages/hydra/_internal/utils.py", line 453, in _run_app
    lambda: hydra.run(
  File "/home/ros/miniconda3/envs/ngdf/lib/python3.7/site-packages/hydra/_internal/utils.py", line 296, in run_and_report
    raise ex
  File "/home/ros/miniconda3/envs/ngdf/lib/python3.7/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/home/ros/miniconda3/envs/ngdf/lib/python3.7/site-packages/hydra/_internal/utils.py", line 456, in <lambda>
    overrides=overrides,
  File "/home/ros/miniconda3/envs/ngdf/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/ros/miniconda3/envs/ngdf/lib/python3.7/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/ros/miniconda3/envs/ngdf/lib/python3.7/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "ngdf/train.py", line 44, in main
    dm.setup()
  File "/home/ros/miniconda3/envs/ngdf/lib/python3.7/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
    fn(*args, **kwargs)
  File "/home/ros/NGDF/ngdf/dataset.py", line 200, in setup
    ids = self.collect_grasps(dset_grasp, objects)
  File "/home/ros/NGDF/ngdf/dataset.py", line 184, in collect_grasps
    (i, "pos", idx) for idx in range(len(dset_grasp[obj]["pos_Ts"]))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ros/miniconda3/envs/ngdf/lib/python3.7/site-packages/h5py/_hl/group.py", line 288, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'pos_Ts' doesn't exist)"
```

**Comment by thomasweng15** [comment]
Sorry for the confusion, the `acronym_perobj` and `acronym_multobj` folders should be structured in the `data/` folder as follows:

```
NGDF
├── ...
├── ngdf
└── data
    |── ...
    |── acronym_perobj
    |   |── ...
    |   |── shape-dataset / dataset.hdf5
    |   └── grasp-dataset / dataset.hdf5 (different file from the one in shape-dataset)
    └── acronym_multobj
        |── ...
        |── shape-dataset / dataset.hdf5
        └── grasp-dataset / dataset.hdf5 (different file from the one in shape-dataset)
```

Are your folders organized similarly? I checked that the dataset.hdf5 files for each dataset exist on Google Drive, I can investigate further to make sure they contain the correct data if you are still encountering issues.

**Comment by paucarre** [comment]
It seems there is just one `dataset.hdf5` 
```
(ngdf) ros@rusalka:~/NGDF/data$ find acronym_multobj -name *.hdf5
acronym_multobj/shape-dataset/dataset.hdf5
```

**Comment by paucarre** [comment]
I downloaded back everything again to make sure things are correct and after having both `dataset.hdf5` I get the following error:
```
OSError: Unable to open file (unable to open file: name = '/home/ros/NGDF/scripts/train/../../data/acronym_multobj/grasp-dataset/../grasps/Bottle_244894af3ba967ccd957eaf7f4edb205_0.012953570261294404.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

It seems this file is present in `acronym_perobj`
```
(ngdf) ros@rusalka:~/NGDF$ find . -name Bottle_244894af3ba967ccd957eaf7f4edb205_0.012953570261294404.h5
./data/acronym_perobj/grasps/Bottle_244894af3ba967ccd957eaf7f4edb205_0.012953570261294404.h5
(ngdf) ros@rusalka:~/NGDF$ 
```

After copying the grasps from single object to multiple objects doing:
```
cp -r ./data/acronym_perobj/grasps/* ./data/acronym_multobj/grasps/
```
I get the following error:
```
  File "/home/ros/miniconda3/envs/ngdf/lib/python3.7/site-packages/trimesh/exchange/load.py", line 623, in parse_file_args
    raise ValueError('string is not a file: {}'.format(file_obj))
ValueError: string is not a file: /home/ros/NGDF/scripts/train/../../data/acronym_multobj/grasp-dataset/../meshes_bullet/Bottle_244894af3ba967ccd957eaf7f4edb205_0.012953570261294404/model_normalized.obj

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
After finding the file in the single object dataset
```
(ngdf) ros@rusalka:~/NGDF$ find . -name Bottle_244894af3ba967ccd957eaf7f4edb205_0.012953570261294404
./data/acronym_perobj/meshes_bullet/Bottle_244894af3ba967ccd957eaf7f4edb205_0.012953570261294404
```
I copied the files:
```
cp -r ./data/acronym_perobj/meshes_bullet/* ./data/acronym_multobj/meshes_bullet
```
I ran the command again and I got this error:
```
OSError: Unable to open file (unable to open file: name = '/home/ros/NGDF/scripts/train/../../data/acronym_multobj/grasp-dataset/../grasps/Bottle_371b604f78300e02d76ab6ff59fe7e10_0.0016918802801247606.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```
Unfortunately this time I coudn't find the file:
```
(ngdf) ros@rusalka:~/NGDF$  find . -name Bottle_371b604f78300e02d76ab6ff59fe7e10_0.0016918802801247606.h5
(ngdf) ros@rusalka:~/NGDF$ 
```
I went to Google Drive and the file wasn't there neither in the single nor the multiobject

**Comment by thomasweng15** [comment]
Hi @paucarre, it sounds like after redownloading you are able to get the files. It might be helpful for me to rename the shape and grasp `dataset.hdf5` files to different names to avoid confusion. 

I looked into the error that you are getting, and I think that the dataloader is trying to load test examples during training due to a discrepancy in my code after cleaning it up. I will release a hotfix for this soon, sorry about that.

**Comment by thomasweng15** [comment]
Hi @paucarre, I think the PR above should fix the issue with the object ids, if you have time to try it and confirm, I can merge it after that. Thank you again for bringing this up!
